FROM node:18-slim

# Update repo dan install Nginx + gettext (untuk envsubst)
RUN apt-get update && apt-get install -y nginx gettext-base && rm -rf /var/lib/apt/lists/*

# Buat folder kerja
WORKDIR /app

# Copy dependency dan install
COPY package*.json ./
RUN pnpm install --production

# Copy source code aplikasi dan config nginx
COPY . .
COPY nginx.conf /etc/nginx/nginx.conf

CMD /bin/bash -c "envsubst '\$PORT' < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf.tmp && mv /etc/nginx/nginx.conf.tmp /etc/nginx/nginx.conf && nginx && node server.js"